---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/014t0/sample_line_notification
    branch: master

- name: timer
  type: time
  source:
    interval: 3m

jobs:
- name: notification
  plan:
    - get: repo
    - get: timer
      trigger: true
    - task: happy-new-year
      file: repo/tasks/line_notify.yml
    